name: drupal10
recipe: drupal10
config:
  webroot: web
  php: "8.1"
  database: mysql
  vhosts:
    - drupal10.lndo.site
  overrides:
    services:
      appserver:
        type: apache
        ssl: true
        config:
          vhosts: |
            <VirtualHost *:80>
              ServerName drupal10.lndo.site
              DocumentRoot /app/web
              <Directory "/app/web">
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
              </Directory>
            </VirtualHost>